In [1]:
import numpy as np

### Generate data

In [85]:
np.random.seed(42)

n_obs = 1
n_features = 2
X = np.random.randint(0, 2, size=(n_features))
y_true = np.logical_or(X[0], X[1]).astype(int)
X, y_true


(array([0, 1]), 1)

### Weights
$y = WX + b$\
$(n \times p) = (n \times n) (n \times p) + (n \times 1)$

In [98]:
def loss(y_pred, y_true):
    return (y_true - y_pred)**2

$\frac{\partial loss}{\partial W} = \frac{\partial loss}{\partial \hat{y}} \frac{\partial \hat{y}}{\partial \sigma} \frac{\partial \sigma}{\partial W}$

In [95]:
np.random.seed(42)

W = np.random.randn(n_features)
b = np.random.randn(1)
y_pred = np.dot(W,X) + b
W.shape, X.shape, b.shape, 
W, X, b, y_pred

(array([ 0.49671415, -0.1382643 ]),
 array([0, 1]),
 array([0.64768854]),
 array([0.50942424]))