# Bonus assignment

**Joris LIMONIER**

---

In this assignment, we try to predict the number of passengers through time. We will use the airline dataset.


## Data Preprocessing

In [14]:
from pathlib import Path

import airline
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import pytorch_lightning as pl
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, TensorDataset
from tqdm import tqdm

pio.templates.default = "plotly_white"


In [15]:
%reload_ext autoreload
%autoreload 2

### Load the dataset


In [16]:
filepath = Path("airline_passenger.txt")
air = pd.read_csv(
  filepath,
  parse_dates=["month"],
  names=["month", "passengers"],
  index_col="month",
  header=0,
  dtype={"passengers": "float32"},
)
air.head()

passengers
month                 
1949-01-01       112.0
1949-02-01       118.0
1949-03-01       132.0
1949-04-01       129.0
1949-05-01       121.0

### Split the dataset into train and test
We use 1/3 of the dataset for testing. The remaining 2/3 is further split into 80% training and 20% validation.

In [17]:
test_size = 1 / 3 
val_size = 0.2 # 20% of the training set is used for validation

train_val, test = train_test_split(air, test_size=test_size, shuffle=False)
train, val = train_test_split(train_val, test_size=val_size, shuffle=False)

We plot the train, validation and test sets with different colors.

In [18]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=train.index, y=train.passengers, name="train", mode="lines"))
fig.add_trace(go.Scatter(x=val.index, y=val.passengers, name="val", mode="lines"))
fig.add_trace(go.Scatter(x=test.index, y=test.passengers, name="test", mode="lines"))
fig.update_layout(title="Airline passengers")
fig.show()


We define constants to use for training:
- `SEQ_LENGTH`: the number of time steps to use for training, *i.e.* the number of previous months to use to predict the next month
- `N_EPOCHS`: the maximum number of epochs to train for
- `BATCH_SIZE`: the batch size to use for training

In [19]:
SEQ_LENGTH = 1
N_EPOCHS = 200
BATCH_SIZE = 2

# Generate train, validation and test sequences
train_sequences = airline.create_sequences(data=train, seq_length=SEQ_LENGTH)
val_sequences = airline.create_sequences(data=val, seq_length=SEQ_LENGTH)
test_sequences = airline.create_sequences(data=test, seq_length=SEQ_LENGTH)

data_module = airline.AirlineDataModule(
  train_sequences=train_sequences,
  val_sequences=val_sequences,
  test_sequences=test_sequences,
  batch_size=BATCH_SIZE,
)
data_module.setup()

# Create the dataset
train_dataset = airline.AirlineDataset(sequences=train_sequences)

# Print an example from the dataset
for item in train_dataset:
  print(f"""Using: {item["sequence"]}""")
  print(f"""The model is trying to predict: {item["label"]}""")
  break


Using: tensor([[112.]])
The model is trying to predict: tensor([118.])


## Model

We define the model and start training.

In [9]:
lr = 0.001 # learning rate

# Create the model
model = airline.PassengerPredictor(n_features=1, lr=lr, weight_decay=1e-2)
model

/home/joris/.local/lib/python3.10/site-packages/torch/nn/modules/rnn.py:62: UserWarning:

dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1



PassengerPredictor(
  (model): PassengerPredictionModel(
    (lstm): LSTM(1, 20, batch_first=True, dropout=0.1)
    (linear): Linear(in_features=20, out_features=1, bias=True)
  )
  (criterion): MSELoss()
)

For monitoring the training, we use TensorBoard. We also save the best model based on the validation loss.

In [11]:
# Create a callback to save the best model
checkpoint_callback = pl.callbacks.ModelCheckpoint(
  monitor="val_loss",
  dirpath="checkpoints",
  save_top_k=1,
  mode="min",
  filename="best_checkpoint",
  verbose=True,
)

# Create a logger for TensorBoard
logger = pl.loggers.TensorBoardLogger("logs", name="airline")

# Create a callback to stop training early if the validation loss does not improve
early_stop_callback = pl.callbacks.EarlyStopping(
  monitor="val_loss",
  patience=10,
  min_delta=400,
  verbose=True,
  mode="min",
)

# Create the trainer
trainer = pl.Trainer(
  logger=logger,
  callbacks=[checkpoint_callback, early_stop_callback],
  max_epochs=N_EPOCHS,
  gpus=1,
)


/media/joris/apps/miniconda/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:474: LightningDeprecationWarning:

Setting `Trainer(gpus=1)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=1)` instead.

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


In [12]:
# Train the model.
trainer.fit(model, data_module)

/media/joris/apps/miniconda/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:613: UserWarning:

Checkpoint directory /media/joris/uca-msc-dsai/dl_computer_vision/assignments/1/checkpoints exists and is not empty.

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type                     | Params
-------------------------------------------------------
0 | model     | PassengerPredictionModel | 1.9 K 
1 | criterion | MSELoss                  | 0     
-------------------------------------------------------
1.9 K     Trainable params
0         Non-trainable params
1.9 K     Total params
0.007     Total estimated model params size (MB)


Sanity Checking: 0it [00:00, ?it/s]

/media/joris/apps/miniconda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py:1609: PossibleUserWarning:

The number of training batches (38) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.



Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Metric val_loss improved. New best score: 103895.609
Epoch 0, global step 38: 'val_loss' reached 103895.60938 (best 103895.60938), saving model to '/media/joris/uca-msc-dsai/dl_computer_vision/assignments/1/checkpoints/best_checkpoint-v1.ckpt' as top 1


Validation: 0it [00:00, ?it/s]

Epoch 1, global step 76: 'val_loss' reached 103574.68750 (best 103574.68750), saving model to '/media/joris/uca-msc-dsai/dl_computer_vision/assignments/1/checkpoints/best_checkpoint-v1.ckpt' as top 1


Validation: 0it [00:00, ?it/s]

Metric val_loss improved by 597.242 >= min_delta = 400. New best score: 103298.367
Epoch 2, global step 114: 'val_loss' reached 103298.36719 (best 103298.36719), saving model to '/media/joris/uca-msc-dsai/dl_computer_vision/assignments/1/checkpoints/best_checkpoint-v1.ckpt' as top 1


Validation: 0it [00:00, ?it/s]

Epoch 3, global step 152: 'val_loss' reached 103110.75781 (best 103110.75781), saving model to '/media/joris/uca-msc-dsai/dl_computer_vision/assignments/1/checkpoints/best_checkpoint-v1.ckpt' as top 1


Validation: 0it [00:00, ?it/s]

Epoch 4, global step 190: 'val_loss' reached 102909.85156 (best 102909.85156), saving model to '/media/joris/uca-msc-dsai/dl_computer_vision/assignments/1/checkpoints/best_checkpoint-v1.ckpt' as top 1


Validation: 0it [00:00, ?it/s]

Metric val_loss improved by 899.141 >= min_delta = 400. New best score: 102399.227
Epoch 5, global step 228: 'val_loss' reached 102399.22656 (best 102399.22656), saving model to '/media/joris/uca-msc-dsai/dl_computer_vision/assignments/1/checkpoints/best_checkpoint-v1.ckpt' as top 1


Validation: 0it [00:00, ?it/s]

Metric val_loss improved by 435.727 >= min_delta = 400. New best score: 101963.500
Epoch 6, global step 266: 'val_loss' reached 101963.50000 (best 101963.50000), saving model to '/media/joris/uca-msc-dsai/dl_computer_vision/assignments/1/checkpoints/best_checkpoint-v1.ckpt' as top 1


Validation: 0it [00:00, ?it/s]

Metric val_loss improved by 417.211 >= min_delta = 400. New best score: 101546.289
Epoch 7, global step 304: 'val_loss' reached 101546.28906 (best 101546.28906), saving model to '/media/joris/uca-msc-dsai/dl_computer_vision/assignments/1/checkpoints/best_checkpoint-v1.ckpt' as top 1


Validation: 0it [00:00, ?it/s]

Epoch 8, global step 342: 'val_loss' reached 101214.87500 (best 101214.87500), saving model to '/media/joris/uca-msc-dsai/dl_computer_vision/assignments/1/checkpoints/best_checkpoint-v1.ckpt' as top 1


Validation: 0it [00:00, ?it/s]

Metric val_loss improved by 632.148 >= min_delta = 400. New best score: 100914.141
Epoch 9, global step 380: 'val_loss' reached 100914.14062 (best 100914.14062), saving model to '/media/joris/uca-msc-dsai/dl_computer_vision/assignments/1/checkpoints/best_checkpoint-v1.ckpt' as top 1


Validation: 0it [00:00, ?it/s]

Epoch 10, global step 418: 'val_loss' reached 100630.14062 (best 100630.14062), saving model to '/media/joris/uca-msc-dsai/dl_computer_vision/assignments/1/checkpoints/best_checkpoint-v1.ckpt' as top 1


Validation: 0it [00:00, ?it/s]

Metric val_loss improved by 557.492 >= min_delta = 400. New best score: 100356.648
Epoch 11, global step 456: 'val_loss' reached 100356.64844 (best 100356.64844), saving model to '/media/joris/uca-msc-dsai/dl_computer_vision/assignments/1/checkpoints/best_checkpoint-v1.ckpt' as top 1


Validation: 0it [00:00, ?it/s]

Epoch 12, global step 494: 'val_loss' reached 100090.67188 (best 100090.67188), saving model to '/media/joris/uca-msc-dsai/dl_computer_vision/assignments/1/checkpoints/best_checkpoint-v1.ckpt' as top 1


## Evaluation

We load the best model and evaluate it on the test set. However, we see that the model doesn't work since it always outputs the same value for all time steps. In our experiments, we tried to use different architectures (hidden size, number of stacked layers, dropout, learning rate, train/val/test splits), but we always got the same result. One possible explanation is that the data should be normalized before training, but I doubt it as, in my opinion, this should only be necessary if we have several features with different scales. In our case, we have only one feature (the number of passengers), so the network should be able to learn the scale.

It is also worth noting that I sent an email to abid.ali@inria.fr and francois.bremond@inria.fr to ask for help, but I didn't get any response. This is a pity as I would have liked to know what I did wrong and I believe there is not much change needed to make the model work.

In [21]:
checkpoint_number = 1
checkpoint_path = f"checkpoints/best_checkpoint-v{checkpoint_number}.ckpt"
trained_model = airline.PassengerPredictor.load_from_checkpoint(
  checkpoint_path=checkpoint_path, n_features=1
)
test_dataset = airline.AirlineDataset(sequences=test_sequences)

sequences = []
labels = []

for item in tqdm(test_dataset):
  sequence = item["sequence"]
  label = item["label"]
  _, prediction = trained_model(sequence)
  print(sequence, prediction, label)


100%|██████████| 47/47 [00:00<00:00, 939.77it/s]

tensor([[315.]]) tensor([32.3449], grad_fn=<AddBackward0>) tensor([301.])
tensor([[301.]]) tensor([32.3449], grad_fn=<AddBackward0>) tensor([356.])
tensor([[356.]]) tensor([32.3449], grad_fn=<AddBackward0>) tensor([348.])
tensor([[348.]]) tensor([32.3449], grad_fn=<AddBackward0>) tensor([355.])
tensor([[355.]]) tensor([32.3449], grad_fn=<AddBackward0>) tensor([422.])
tensor([[422.]]) tensor([32.3449], grad_fn=<AddBackward0>) tensor([465.])
tensor([[465.]]) tensor([32.3449], grad_fn=<AddBackward0>) tensor([467.])
tensor([[467.]]) tensor([32.3449], grad_fn=<AddBackward0>) tensor([404.])
tensor([[404.]]) tensor([32.3449], grad_fn=<AddBackward0>) tensor([347.])
tensor([[347.]]) tensor([32.3449], grad_fn=<AddBackward0>) tensor([305.])
tensor([[305.]]) tensor([32.3449], grad_fn=<AddBackward0>) tensor([336.])
tensor([[336.]]) tensor([32.3449], grad_fn=<AddBackward0>) tensor([340.])
tensor([[340.]]) tensor([32.3449], grad_fn=<AddBackward0>) tensor([318.])
tensor([[318.]]) tensor([32.3449], gra